CREATE TABLE site (
id SERIAL PRIMARY KEY,
city VARCHAR(100) NOT NULL
);

CREATE TABLE service (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE users (
id SERIAL PRIMARY KEY,
firstName VARCHAR(255) NOT NULL,
lastName VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
fix VARCHAR (255),
mobile VARCHAR (255) NOT NULL,
password VARCHAR(255) NOT NULL,
isAdmin BOOLEAN DEFAULT false
);

ALTER TABLE service ADD COLUMN site_id INTEGER REFERENCES site(id);
ALTER TABLE users ADD COLUMN service_id INTEGER REFERENCES service(id);

